version: '2.1'

services:
  redis:
    container_name: cache
    image: redis
    expose:
      - 6379
    volumes:
      - ../data/redis:/data
    restart: always
    
  caching-redis:
    container_name: app
    image: caching-redis
    links: 
      - redis
    build: .
    environment:
      NODE_ENV: production
      REDIS_URL: redis://cache

    ports:
      - 3000:3000